#PROBLEM 1
print("----- MY PROFILE -----")
print()
input("Name : ")
input("Age : ")
input("City : ")
print()
print("----------------------")
print()
#PROBLEM 2
Fav_Food=input("Fav Food : ")
Fav_Movie=input("Fav Movie : ")
Fav_Lang=input("Fav Programming Lang : ")
print("your favourites")
print(Fav_Food)
print(Fav_Movie)
print(Fav_Lang)
print()
#PROBLEM 3
name=input("Enter your name: ")
college=input("Enter college name: ")
branch=input("enter branch : ")
year=input("enter year : ")
print("""====================
   STUDENT CARD
====================""")
print("Name    : ",name)
print("College : ",college)
print("Branch  : ",branch)
print("Year    : ",year)
print()
#PROBLEM 4
name=input("Enter your name : ")
dream_job=input("Enter your desired job : ")
country=input("Desired travelling country : ")
print()
print("Hello ",name)
print("One day you'll become a ",dream_job)
print("and work in ",country)
print()
print("Keep learning every day! 🚀")